= streams-perf

A bare bones example of how to setup streams (Kafka) v1.2 on openshift using an external TLS client which uses client side TLS for authorization.
Note these instructions use the following configuration:


* Red Hat internal https://docs.google.com/document/d/1HOahEzLRdKiKC-TSfBaTGtoi1jiJetkh8CDF_pSeCaw/edit[env]
* project/namespace: kafka
* kafka cluster name: my-cluster
* topics: my-topic

This project assumes the following are installed

* oc client
* java 8
* maven

NOTE: In order to install the cluster operator a user with cluster administrator

NOTE: If projects have quotas, make sure you have enough resources this was tested with 10 CPUs and 12 G of memory.  These limits can be verified with the command 'oc describe quota kafka-quota'

Thanks to Josh Reagan and his blog http://blog.joshdreagan.com/2019/05/30/streaming_in_the_cloud_with_camel_and_strimzi/[post] for all the good information and original client code.

== Install cluster operator

After logging into openshift via the cli create a new project
----
oc new-project kafka
----

Create the cluster operator in the kafka project/namespace
----
oc apply -f install/cluster-operator -n kafka
oc apply -f examples/templates/cluster-operator -n kafka
----

== Install and configure kafka cluster

Create the kafka cluster in the name space
----
oc apply -f examples/kafka/kafka-persistent.yaml
----

Create a topic (make sure the 3 zookeeper and 3 kafka pods are started)
----
oc apply -f examples/topic/kafka-topic.yaml
----

Create TLS based users
----
oc apply -f examples/user/kafka-user.yaml
oc apply -f examples/user/kafka-user-consumer.yaml
----

== Install and configure client

In the `producer` directory modify the `run.sh` file

* Replace `CAMEL_COMPONENT_KAFKA_CONFIGURATION_BROKERS` with your kafka bootstrap route as in this link:route.png[image].

* Replace `KAFKA_CLUSTER_CRT` value with the one in your cluster.  You can retrieve it with the command. Paste the contents of the file into the value for `KAFKA_CLUSTER_CRT`

----
extract secret/kafka-test-cluster-ca-cert --keys=ca.crt --to=- > ca.crt
----

* Replace `KAFKA_USER_CRT` and `KAFKA_USER_KEY` values with the information from the `my-user` user. (USER.CRT = KAFKA_USER_CRT USER.KEY=KAFKA_USER_KEY).
Use the copy to clip board icon located to the right on each values row (See openshift link:crtKey.png[image])

* Be sure to save the file.

== Install and run producer client
In the `consumer` directory build and run the consumer.
----
mvn clean install
./run.sh
----

In the terminal output you should see result similar to:
----
17:56:58.541 [Camel (camel-kafka-tls) thread #1 - timer://kickstartmyroute] INFO  route1 - Sending message: [Sending message: [Mon Aug 19 17:56:58 MST 2019]]
----