= streams-perf

A bare bones example of how to setup streams (Kafka) v1.2 on openshift using an external TLS client which uses client side TLS for authorization.
Note these instructions use the following configuration:


* Red Hat internal https://docs.google.com/document/d/1HOahEzLRdKiKC-TSfBaTGtoi1jiJetkh8CDF_pSeCaw/edit[env]
* project/namespace: kafka
* kafka cluster name: my-cluster
* topics: my-topic (20 partitions / 3 replicas)

This project assumes the following are installed

* oc client
* java 8
* maven

NOTE: In order to install the cluster operator a user with cluster administrator

NOTE: If projects have quotas, make sure you have enough resources this was tested with 10 CPUs and 12 G of memory.  These limits can be verified with the command 'oc describe quota kafka-quota'

Thanks to Josh Reagan and his blog http://blog.joshdreagan.com/2019/05/30/streaming_in_the_cloud_with_camel_and_strimzi/[post] for all the good information and original client code.

== Install cluster operator

After logging into openshift via the cli create a new project
----
oc new-project kafka
----

Create the cluster operator in the kafka project/namespace
----
oc apply -f install/cluster-operator -n kafka
oc apply -f examples/templates/cluster-operator -n kafka
----

== Install and configure kafka cluster

Create the kafka cluster in the name space
----
oc apply -f examples/kafka/kafka-persistent.yaml
----

Create a topic (make sure the 3 zookeeper and 3 kafka pods are started)
----
oc apply -f examples/topic/kafka-topic.yaml
----

Create TLS based users
----
oc apply -f examples/user/kafka-user.yaml
----

== Install and configure perf clients


== Delete cluster
The kafka cluster can be deleted with
----
oc delete kafka my-cluster
----